### ISSUE TITLE
default to running with `--in-place` in pre-commit hook

### ISSUE THREAD

**Issue by graingert** [PyCQA/autoflake#78]

**Comment by spookylukey** [comment]
At the very least the hook should pass `-c` argument so that you get notified of issues.

The current behaviour of the hook without arguments is that it **always** prints:
```
autoflake................................................................Passed
```

Which is not very helpful :-)

But I'd also prefer defaulting to `--in-place` - given the tool is about automatically making changes. If I just want notifications, then I can use flake8 as a commit hook.

**Comment by max-sixty** [comment]
Agree — would it be reasonable to have the suggested entry at https://github.com/myint/autoflake/pull/62#issue-552588261 be the default?
